version: "3"
services:

  vertcoind:
    image: lukechilds/vertcoind
    expose:
      - "8332"
    ports:
      - "8333:8333"
    volumes:
      - ./data/vertcoind:/data
    command: -rpcuser=electrum -rpcpassword=electrum

  electrumx:
    image: lukechilds/electrumx
    ports:
      - "55002:50002"
    volumes:
      - ./data/electrumx:/data
    environment:
      - DAEMON_URL=http://electrum:electrum@vertcoind:8332
      - COIN=Vertcoin
